# Generated by Django 4.2.8 on 2023-12-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, unique=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тема урока')),
                ('theory', models.TextField(verbose_name='Теория')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тема')),
                ('lessons', models.ManyToManyField(blank=True, related_name='lessons_from_topic', to='lessons.lesson', verbose_name='Уроки')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('correct_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correct_option', to='lessons.answer', verbose_name='Верный ответ')),
                ('options', models.ManyToManyField(related_name='options', to='lessons.answer', verbose_name='Варианты ответа')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='questions_from_lesson', to='lessons.question', verbose_name='Вопросы'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Язык')),
                ('description', models.TextField(verbose_name='Описание')),
                ('topics', models.ManyToManyField(blank=True, related_name='topics_from_language', to='lessons.topic', verbose_name='Темы')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'языки',
            },
        ),
    ]
