# Generated by Django 4.2.8 on 2023-12-08 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='lessons.topic', verbose_name='Тема'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_of_question', to='lessons.lesson', verbose_name='Урок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='language', to='lessons.language', verbose_name='Язык'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Урок'),
        ),
    ]
