# Generated by Django 4.2.8 on 2024-02-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_language_topics_remove_lesson_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions_correct_option', to='lessons.answer', verbose_name='Верный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_of_lesson', to='lessons.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(to='lessons.answer', verbose_name='Варианты ответа'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='lessons.language', verbose_name='Язык'),
        ),
    ]
