# Generated by Django 4.2.8 on 2024-06-14 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_answer_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'прогресс пользователя', 'verbose_name_plural': 'прогрессы пользователей'},
        ),
        migrations.AlterField(
            model_name='progress',
            name='last_completed_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessons.lesson', verbose_name='последний                                                 завершенный урок'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='wrong_answers',
            field=models.ManyToManyField(blank=True, to='lessons.question', verbose_name='вопросы, на которые                                             пользователь ответил неверно'),
        ),
    ]
