# Generated by Django 4.2.8 on 2024-06-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_progress_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('tg_user', 'language'), name='unique_language_user'),
        ),
    ]
