# Generated by Django 4.2.8 on 2024-06-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_remove_progress_unique_language_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='tg_user_id',
            field=models.PositiveBigIntegerField(default=0, verbose_name='id пользователя'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('language', 'tg_user_id'), name='unique_language_tguser'),
        ),
    ]
