# Generated by Django 4.2.13 on 2024-06-25 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_progress_tg_user_id_progress_unique_language_tguser'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='topic',
        #     name='language',
        # ),
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_topic_lesson',
        ),
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_topic_lessonsnumber',
        ),
        migrations.AddField(
            model_name='lesson',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.language', verbose_name='язык'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer1',
            field=models.CharField(default=1, max_length=255, verbose_name='Вариант 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer2',
            field=models.CharField(default=1, max_length=255, verbose_name='Вариант 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer3',
            field=models.CharField(default=1, max_length=255, verbose_name='Вариант 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default=1, max_length=255, verbose_name='Верный ответ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='serial_number',
            field=models.PositiveIntegerField(verbose_name='Номер урока в языке'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='question',
            order_with_respect_to='lesson',
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['language', 'tg_user_id'], name='lessons_pro_languag_101fd6_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('language', 'title'), name='unique_language_lesson'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('language', 'serial_number'), name='unique_language_lessonsnumber'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AlterOrderWithRespectTo(
            name='lesson',
            order_with_respect_to='language',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
