# Generated by Django 4.2.13 on 2024-07-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_progress_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['lesson', 'serial_number'], name='lessons_que_lesson__8c050a_idx'),
        ),
    ]
