# Generated by Django 4.2.8 on 2024-08-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_question_lessons_que_lesson__8c050a_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(max_length=4096, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='theory',
            field=models.TextField(max_length=4096, verbose_name='Теория'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer1',
            field=models.CharField(max_length=64, verbose_name='Вариант 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2',
            field=models.CharField(max_length=64, verbose_name='Вариант 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.CharField(max_length=64, verbose_name='Вариант 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=64, verbose_name='Верный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=4096, verbose_name='Вопрос'),
        ),
    ]
