repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: isort
        name: isort
        entry: isort .
        language: system
        types: [python]

    -   id: flake8
        name: flake8
        entry: flake8 .
        language: system
        types: [python]