services:

  postgres:
    container_name: BecomeaPRO_postgres
    image: postgres:16.4-alpine
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env


  backend:
    container_name: BecomeaPRO_backend
    build: ../backend/
    restart: always
    volumes:
      - static_value:/app/static/
    depends_on:
      - postgres
    env_file:
      - .env


  nginx:
    container_name: BecomeaPRO_nginx
    image: nginx:1.27.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - backend


  # redis:
  #   container_name: BecomeaPRO_redis
  #   image: redis:7.4-alpine
  #   restart: on-failure
  #   volumes:
  #     - redis_data:/data
  #   env_file:
  #     - .env


  bot:
    container_name: BecomeaPRO_bot
    build: ../bot/
    restart: always
    depends_on:
      - nginx
      # - redis
    env_file:
      - .env


volumes:
  postgres_data:
  static_value:
  # redis_data:
