# Generated by Django 4.2.8 on 2024-06-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0007_progress_unique_language_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.PositiveBigIntegerField(unique=True, verbose_name='id пользователя')),
                ('progress', models.ManyToManyField(blank=True, related_name='tguser', to='lessons.progress', verbose_name='прогрессы пользователя')),
            ],
            options={
                'verbose_name': 'пользователь бота',
                'verbose_name_plural': 'пользователи бота',
            },
        ),
    ]
