# Generated by Django 4.2.8 on 2024-06-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'пользователь бота', 'verbose_name_plural': 'пользователи бота'},
        ),
    ]
