name: CI

on: push

jobs:
  linting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
      
    - name: Install linters
      run: python -m pip install flake8 isort
    - name: Run flake
      run: flake8 .
    - name: Run isort
      run: isort . --check-only
