name: Django CI

on: push

jobs:
  linting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
      
    - name: Install linters
      run: |
        cd backend/
        python -m pip install flake8 isort
    - name: Run linters
      run: |
        flake8 . 
        isort .
